/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-11-12 11:05:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\n");
      out.write("<title>Coupang Join</title>\n");
      out.write("<style>\n");
      out.write("* {\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\twidth: 460px;\n");
      out.write("\tmargin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo {\n");
      out.write("\tmargin-top: 60px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 100%;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("/* Style the input container */\n");
      out.write(".input-container {\n");
      out.write("\tdisplay: flex;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tmargin-top: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Style the form icons */\n");
      out.write(".icon {\n");
      out.write("\tpadding: 10px;\n");
      out.write("\tbackground: #ddd;\n");
      out.write("\tcolor: white;\n");
      out.write("\tmin-width: 50px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tborder: solid 1px #bbb;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Style the input fields */\n");
      out.write(".input-field {\n");
      out.write("\twidth: 100%;\n");
      out.write("\tpadding: 10px;\n");
      out.write("\toutline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".alert {\n");
      out.write("\tdisplay:none;\n");
      out.write("\twidth:100%;\n");
      out.write("\tmargin-top:5px;\n");
      out.write("\tmargin-bottom: 15px;\n");
      out.write("\tcolor:red;\n");
      out.write("\tfont-size:13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".input-field:focus {\n");
      out.write("\tborder: 2px solid dodgerblue;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".input-container:focusout {\n");
      out.write("\tborder: 2px solid red;\n");
      out.write("}\n");
      out.write(".join_agree {\n");
      out.write("\tmargin-top: 5px;\n");
      out.write("\tfont-size: 13px;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tfont-size: 13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".join__agree-link {\n");
      out.write("\tcolor: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Set a style for the submit button */\n");
      out.write(".btn {\n");
      out.write("\tbackground-color: #0074E9;\n");
      out.write("\tcolor: white;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tpadding: 15px 20px;\n");
      out.write("\tborder: none;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tpadding: 15px 20px;\n");
      out.write("\tmargin-top:15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer {\n");
      out.write("\tmargin-top: 20px;\n");
      out.write("\tfont-size: 12px;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("\t$(\".input-field\").blur(funtion(){\n");
      out.write("\t\t$(\".alert\").css({\n");
      out.write("\t\t\t\"display\":\"block\"\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<form action=\"login\" method=\"post\">\n");
      out.write("\t\t<h1 class=\"logo\">\n");
      out.write("\t\t\t<a href=\"https://www.coupang.com/\"><img src=\"img/logo.png\"></a>\n");
      out.write("\t\t</h1>\n");
      out.write("\t\t<div class=\"input-container\">\n");
      out.write("\t\t\t<label class=\"icon\" for=\"email\"><i class=\"far fa-envelope\"></i></label>\n");
      out.write("\t\t\t<input class=\"input-field\" type=\"email\" placeholder=\"아이디(이메일)\" id=\"email\" name=\"email\">\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"alert\">이메일을 입력하세요.</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"input-container\">\n");
      out.write("\t\t\t<label class=\"icon\" for=\"pw\"><i class=\"fas fa-lock\"></i></label> \n");
      out.write("\t\t\t<input class=\"input-field\" type=\"password\"\tplaceholder=\"비밀번호(영문 숫자 특수문자 2가지 이상 6~15자 이내)\" id=\"pw\" name=\"pw\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"alert\">비밀번호는 6~15자 이내로 입력하셔야 합니다.</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"input-container\">\n");
      out.write("\t\t\t<label class=\"icon\" for=\"pw_check\"><i class=\"fas fa-unlock-alt\"></i></label> \n");
      out.write("\t\t\t<input class=\"input-field\" type=\"password\" placeholder=\"비밀번호 확인\" id=\"pw_check\" name=\"pw_check\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"alert\">비밀번호가 일치하지 않습니다.</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"input-container\">\n");
      out.write("\t\t\t<label class=\"icon\" for=\"name\"><i class=\"far fa-user\"></i></label> \n");
      out.write("\t\t\t<input class=\"input-field\" type=\"text\" placeholder=\"이름\" id=\"name\" name=\"name\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"alert\">이름을 정확히 입력하세요.</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"input-container\">\n");
      out.write("\t\t\t<label class=\"icon\" for=\"phone\"><i class=\"fas fa-mobile-alt\"></i></label>\n");
      out.write("\t\t\t<input class=\"input-field\" type=\"tel\" placeholder=\"휴대폰 번호\" id=\"phone\" name=\"phone\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"alert\">휴대폰 번호를 정확하게 입력하세요.</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<button type=\"submit\" class=\"btn\">동의하고 가입하기</button>\n");
      out.write("\t\t<div class=\"join_agree\">\n");
      out.write("\t\t\t본인은 <strong>만 14세 이상</strong>이며, <a class=\"join__agree-link\" href=\"#\">쿠팡이용약관</a>,\n");
      out.write("\t\t\t<a class=\"join__agree-link\" href=\"#\">전자금융거래이용약관</a>, <a class=\"join__agree-link\" href=\"#\">개인정보 수집 및 이용</a>, \n");
      out.write("\t\t\t<a class=\"join__agree-link\" href=\"#\">개인정보 제공</a> 내용을 확인 하였으며, <strong>동의합니다.</strong>\n");
      out.write("\t</form>\n");
      out.write("\t<footer>&copy;Coupang Corp. All rights reserved.</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
